import type {
  AlertSeverity,
  AlertStatus,
  SecurityAlert,
} from '../../../core/types/alerts'

type AlertFixture = readonly [
  title: string,
  category: string,
  affectedAsset: string,
  domainController: string,
  description: string,
  recommendedAction: string,
]

const fixtures = [
  [
    'DCSync replication requested by non-controller',
    'Credential Access',
    'svc-sync',
    'DC01.corp.example.com',
    'A service account requested directory replication rights from a workstation.',
    'Disable the account, revoke replication rights, and rotate exposed credentials.',
  ],
  [
    'Golden Ticket indicators found',
    'Persistence',
    'KRBTGT',
    'DC02.corp.example.com',
    'A Kerberos ticket used an anomalous lifetime and an unknown encryption key.',
    'Contain the source host and perform a controlled double rotation of KRBTGT.',
  ],
  [
    'AdminSDHolder permissions modified',
    'Privilege Escalation',
    'CN=AdminSDHolder,CN=System',
    'DC01.corp.example.com',
    'An unapproved access control entry was added to AdminSDHolder.',
    'Remove the entry and review protected groups for inherited access.',
  ],
  [
    'Domain controller security logs cleared',
    'Defense Evasion',
    'DC03',
    'DC03.corp.example.com',
    'Security event logs were cleared outside the maintenance window.',
    'Preserve remote telemetry and investigate the initiating administrator session.',
  ],
  [
    'Kerberoasting activity detected',
    'Credential Access',
    'svc-backup',
    'DC02.corp.example.com',
    'Many service tickets using RC4 were requested by one endpoint.',
    'Rotate affected service credentials and require AES Kerberos encryption.',
  ],
  [
    'Domain Admins membership changed',
    'Privilege Escalation',
    'Domain Admins',
    'DC01.corp.example.com',
    'A dormant account was added to the Domain Admins group.',
    'Remove unauthorized membership and validate the account owner activity.',
  ],
  [
    'Unconstrained delegation enabled',
    'Persistence',
    'APP-LEGACY-01',
    'DC02.corp.example.com',
    'A computer account was configured to trust delegation for any service.',
    'Disable unconstrained delegation and migrate the application to constrained delegation.',
  ],
  [
    'Suspicious NTLM relay pattern',
    'Lateral Movement',
    'FILE-01',
    'DC03.corp.example.com',
    'NTLM authentications moved rapidly between a workstation and file server.',
    'Isolate the workstation and enforce SMB signing on affected systems.',
  ],
  [
    'Password spray against privileged users',
    'Initial Access',
    'Privileged Users',
    'DC01.corp.example.com',
    'Low-volume failures targeted many privileged accounts from one address.',
    'Block the source and require password resets for accounts with successful follow-up logons.',
  ],
  [
    'LDAP signing not required',
    'Configuration',
    'Default Domain Controllers Policy',
    'DC02.corp.example.com',
    'A policy change allowed unsigned LDAP binds on domain controllers.',
    'Restore LDAP signing requirements and identify clients using insecure binds.',
  ],
  [
    'New shadow credential added',
    'Persistence',
    'j.santos',
    'DC03.corp.example.com',
    'A key credential was written to a user outside certificate enrollment workflows.',
    'Remove the key credential and revoke sessions belonging to the account.',
  ],
  [
    'SIDHistory added to user',
    'Privilege Escalation',
    'contractor.temp',
    'DC01.corp.example.com',
    'A privileged SID was added to SIDHistory on a standard user.',
    'Clear the unauthorized value and audit the operator that changed it.',
  ],
  [
    'Certificate template made vulnerable',
    'Credential Access',
    'UserAuthentication',
    'DC02.corp.example.com',
    'Enrollment permissions and subject controls now permit arbitrary identities.',
    'Restrict enrollment and invalidate certificates issued after the change.',
  ],
  [
    'GPO linked to Domain Controllers changed',
    'Policy Change',
    'Default Domain Controllers Policy',
    'DC03.corp.example.com',
    'Audit policy settings were weakened in a domain-controller-linked GPO.',
    'Restore approved policy and review all edits from the same session.',
  ],
  [
    'Machine account quota increased',
    'Configuration',
    'corp.example.com',
    'DC01.corp.example.com',
    'The machine account quota was raised above the approved baseline.',
    'Restore the baseline and review recently created computer accounts.',
  ],
  [
    'Suspicious RBCD configuration',
    'Lateral Movement',
    'SQL-CLUSTER-01',
    'DC02.corp.example.com',
    'A workstation received resource-based constrained delegation rights to a server.',
    'Remove the delegation entry and investigate both computer accounts.',
  ],
  [
    'Privileged account enabled after hours',
    'Account Management',
    'breakglass-admin',
    'DC03.corp.example.com',
    'An emergency account was enabled without an approved incident.',
    'Disable the account and validate all actions taken during the enabled period.',
  ],
  [
    'Repeated smart-card bypass logons',
    'Authentication',
    'finance-admin',
    'DC01.corp.example.com',
    'A smart-card-required account authenticated using a password-compatible flow.',
    'Revoke active tickets and verify smart-card enforcement on the account.',
  ],
  [
    'DNS record redirected internally',
    'Defense Evasion',
    'intranet.corp.example.com',
    'DC02.corp.example.com',
    'A sensitive internal DNS record was changed to an unmanaged address.',
    'Restore the approved record and inspect the host at the destination address.',
  ],
  [
    'Inactive privileged account used',
    'Account Management',
    'legacy-schema-admin',
    'DC03.corp.example.com',
    'An account unused for nine months performed a privileged directory read.',
    'Disable the account and investigate the source device and credential exposure.',
  ],
  [
    'Weak service account password policy',
    'Configuration',
    'svc-reporting',
    'DC01.corp.example.com',
    'A service account was exempted from password expiration without compensating controls.',
    'Move the account to a managed service account and remove the exemption.',
  ],
  [
    'Excessive failed trust authentications',
    'Authentication',
    'EMEA child trust',
    'DC02.corp.example.com',
    'Trust authentication failures exceeded the normal hourly baseline.',
    'Validate trust health and block unexpected sources attempting authentication.',
  ],
  [
    'Stale computer account authenticated',
    'Account Management',
    'KIOSK-044',
    'DC03.corp.example.com',
    'A disabled-location computer account authenticated after extended inactivity.',
    'Disable the computer account and locate or isolate the physical device.',
  ],
  [
    'Sensitive OU inheritance enabled',
    'Policy Change',
    'Tier 0 Admins OU',
    'DC01.corp.example.com',
    'Permission inheritance was enabled on the protected Tier 0 organizational unit.',
    'Disable inheritance and compare permissions against the approved baseline.',
  ],
  [
    'Anonymous LDAP bind observed',
    'Discovery',
    'DC02',
    'DC02.corp.example.com',
    'A legacy scanner performed an anonymous LDAP directory query.',
    'Configure authenticated scanning and reject anonymous LDAP binds.',
  ],
  [
    'Group Policy preference secret found',
    'Credential Exposure',
    'Legacy Printers GPO',
    'DC03.corp.example.com',
    'A Group Policy preference file contains an encrypted password value.',
    'Remove the preference, rotate the credential, and delete replicated copies.',
  ],
  [
    'Dormant group contains active members',
    'Hygiene',
    'Legacy Server Operators',
    'DC01.corp.example.com',
    'An obsolete delegated group still grants rights to active users.',
    'Remove memberships and retire the group after owner confirmation.',
  ],
  [
    'Unsupported encryption type requested',
    'Authentication',
    'NAS-02',
    'DC02.corp.example.com',
    'A storage appliance requested DES-compatible Kerberos authentication.',
    'Upgrade the appliance and disable legacy Kerberos encryption types.',
  ],
  [
    'Unexpected schema query volume',
    'Discovery',
    'DEV-WKS-118',
    'DC03.corp.example.com',
    'A developer workstation queried the directory schema far above baseline.',
    'Validate developer activity and scan the workstation for reconnaissance tooling.',
  ],
  [
    'Computer account password overdue',
    'Hygiene',
    'LAB-PC-221',
    'DC01.corp.example.com',
    'A laboratory computer has not rotated its machine password for six months.',
    'Repair the domain trust and confirm automatic machine password rotation.',
  ],
  [
    'Time skew nearing Kerberos limit',
    'Availability',
    'DC02',
    'DC02.corp.example.com',
    'Domain controller time differs from the authoritative source by four minutes.',
    'Restore time synchronization and verify the forest root PDC emulator source.',
  ],
  [
    'Orphaned SPN detected',
    'Hygiene',
    'HTTP/oldportal',
    'DC03.corp.example.com',
    'A service principal name references a retired application account.',
    'Confirm retirement and remove the stale service principal name.',
  ],
] satisfies readonly AlertFixture[]

const severities = [
  'critical',
  'high',
  'medium',
  'low',
] as const satisfies readonly AlertSeverity[]
const statuses = [
  'open',
  'in_review',
  'resolved',
  'suppressed',
] as const satisfies readonly AlertStatus[]

export const mockAlerts: SecurityAlert[] = fixtures.map((fixture, index) => ({
  id: `ALT-${String(index + 1).padStart(3, '0')}`,
  title: fixture[0],
  severity: severities[index % severities.length]!,
  status: statuses[index % statuses.length]!,
  category: fixture[1],
  affectedAsset: fixture[2],
  domainController: fixture[3],
  detectedAt: new Date(
    Date.UTC(
      2026,
      6,
      18 - Math.floor(index / 4),
      8 + (index % 10),
      (index * 7) % 60,
    ),
  ).toISOString(),
  description: fixture[4],
  recommendedAction: fixture[5],
}))
